set(CMAKE_SYSTEM_NAME "Android")
set(CMAKE_SYSTEM_PROCESSOR "aarch64")

set(TOOLCHAIN_PREFIX "${CMAKE_SYSTEM_PROCESSOR}-unknown-linux-android")

set(TOOLCHAIN_PATH "$ENV{PINO_HOME}")

if ("${TOOLCHAIN_PATH}" STREQUAL "")
	file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}" TOOLCHAIN_PATH)
	set(TOOLCHAIN_PATH "${TOOLCHAIN_PATH}/../../../../..")
endif()

set(ANDROID_PLATFORM_LEVEL "21")

set(CMAKE_C_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}${ANDROID_PLATFORM_LEVEL}-gcc" CACHE FILEPATH "cc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}${ANDROID_PLATFORM_LEVEL}-g++" CACHE FILEPATH "c++")
set(CMAKE_AR "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-ar" CACHE FILEPATH "ar")
set(CMAKE_RANLIB "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-ranlib" CACHE FILEPATH "ranlib")
set(CMAKE_STRIP "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-strip" CACHE FILEPATH "strip")
set(CMAKE_OBJCOPY "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objcopy" CACHE FILEPATH "objcopy")
set(CMAKE_OBJDUMP "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-objdump" CACHE FILEPATH "objdump")
set(CMAKE_NM "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}-nm" CACHE FILEPATH "nm")

set(PINO_FIND_ROOT_PATH "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}${ANDROID_PLATFORM_LEVEL}" CACHE FILEPATH "sysroot")

set(NZ "$ENV{PINO_NZ}")
set(NZ_FIND_ROOT_PATH "")

if ("${NZ}" STREQUAL "1" OR "${NZ}" STREQUAL "true")
	set(NZ_FIND_ROOT_PATH "${TOOLCHAIN_PATH}/${TOOLCHAIN_PREFIX}${ANDROID_PLATFORM_LEVEL}/lib/nouzen/sysroot")
	set(PKG_CONFIG_EXECUTABLE "${TOOLCHAIN_PATH}/bin/${TOOLCHAIN_PREFIX}${ANDROID_PLATFORM_LEVEL}-pkg-config" CACHE FILEPATH "pkg-config")
else()
	set(PKG_CONFIG_EXECUTABLE "" CACHE FILEPATH "pkg-config")
endif()

set(CMAKE_FIND_ROOT_PATH "${PINO_FIND_ROOT_PATH};${NZ_FIND_ROOT_PATH}" CACHE FILEPATH "sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

include("${CMAKE_CURRENT_LIST_DIR}/android-support.cmake")
